version: '3'
services:
  client:
    image: node:12.11.0-alpine
    container_name: client
    environment:
      PORT: 3000
      HOST: 0.0.0.0
    ports:
      - "3000:3000"
    working_dir:
      /src
    volumes:
      - ./client:/src
    command: [sh, -c, yarn install --network-timeout 1000000 && yarn dev]
  server:
    image: node:12.11.0-alpine
    container_name: server
    ports:
      - 4000:4000
    working_dir:
      /server
    volumes:
      - ./server:/server
    command: [sh, -c, yarn install --network-timeout 1000000 && yarn start:dev]