version: '3'
services:
  app:
    image: node:12.11.0-alpine
    container_name: app
    environment:
      PORT: 3000
      HOST: 0.0.0.0
    ports:
      - "3000:3000"
    working_dir:
      /src
    volumes:
      - ./app:/src
    command: [sh, -c, yarn install && yarn dev]
  api:
    image: node:12.11.0-alpine
    container_name: api
    ports:
      - 4000:4000
    working_dir:
      /api
    volumes:
      - ./api:/api
    command: [sh, -c, yarn install && yarn start:dev]
  # mongo:
  #   image: mongo
  #   restart: always
  #   ports:
  #     - 27017:27017
  #     - 27018:27018
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
  #     MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
  #   volumes:
  #     - ./db:/data/db
  #     - ./configdb:/data/configdb
  # mongo-express:
  #     image: mongo-express
  #     restart: always
  #     ports:
  #       - 8081:8081
  #     environment:
  #       ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
  #       ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}